// log version
console.log("nightTab version", version.get());
data.init();
state.init();
bookmarks.init();
theme.init();
menu.init();
link.init();
control.init();
greeting.init();
transitional.init();
date.init();
clock.init();
keyboard.init();
layout.init();
background.init();
search.init();
title.init();
header.init();
version.init();
